### ISSUE TITLE
can't find picture if Path too long. Must be installed near ~

### ISSUE THREAD

**Issue by MadStarr** [finscn/iCreator#3]
Didn't look at the code but path is truncated at 36 char and 
convert can't find the image.

I moved the converting directory with original large icon in home directory and it works

convert: unable to open image '/Users/Shared/AppleDev/XYZDev/logos': No such file or directory @ error/blob.c/OpenBlob/3094.

**Comment by finscn** [comment]
I will try to find the issue. Thanks

**Comment by finscn** [comment]
fixed.
